import type { NextPage, NextApiRequest, NextApiResponse } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import getCharacters from './api/CharactersApi'

function Home() {
  
  const [dataCharacters, setState] = useState([] as any[])
  const [dataSearch, setSearch] = useState('')
   
  async function promises() {
    
    const { data } = await getCharacters()
      .then(response => response.json());
          const dataCharacters = data.results;
      setState(dataCharacters);

    return dataCharacters
  }

  useEffect(() => {
    promises()
  }, [])

  //const filterDataCharacters = dataCharacter.filter((list) => list.startsWith(dataSearch))
    
  console.log("test:", dataCharacters)
  console.log(dataSearch)

  return (
 

    <div className={styles.container}>
      <Head>
        <title>Marvel App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Marvel Comics!
        </h1>

        <p className={styles.description}>
          Great Characters of Marvel!
          <br /><br />          
          <input
            type={'text'}
            className={styles.inputSearch}
            value={dataSearch}
            onChange={((e) => setSearch(e.target.value))}
            placeholder={'Search ...'}
          />
        </p>        

        <ul>
        
          {dataCharacters.map((list) => 
            
            <div className={styles.grid} key={list.id}>
              <div className={styles.card}>
                <h2 className={styles.Cardtitle}>{list.name}</h2>
                
                <img 
                  className={styles.image}
                  src={`${list.thumbnail.path}/portrait_xlarge.${list.thumbnail.extension}`} 
                  alt={list.name}
                />
                                
                <Link href={`/characters/${list.id}`}><button className={styles.button}>Detalhes</button></Link>                                                              
                
              </div>          
            </div>
          
          )}

        </ul>                       
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
   
  )
}

export default Home
