import React from 'react'

function Head() {
    return (
        <div>
            <title>Marvel App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </div>        
    )
}

export default Head;
